server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /etc/promtail/positions.yaml

clients:
  - url: http://{{ monitoring_ip }}:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker-dymanic
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      # Динамически переопределяем job в зависимости от имени контейнера
      - source_labels: [__meta_docker_container_name]
        target_label: job
        regex: '/(.*)'
        replacement: '${1}-container-logs'

      - source_labels: [__meta_docker_container_name]
        target_label: container_name
        regex: '/(.*)'
        replacement: '${1}'

      - source_labels: [__meta_docker_container_log_stream]
        target_label: stream

      - source_labels: [__meta_docker_container_id]
        target_label: container_id

      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: compose_service

      - source_labels: [__meta_docker_container_label_com_docker_compose_project]
        target_label: compose_project

    pipeline_stages:
      - docker: {}


 # ПРИМЕР ДЖОБА ДЛЯ backend приложения
 # - job_name: backend-app-log
 #  static_configs:
 #     - targets: ['localhost']
 #       labels:
 #         job: backend-app-log
 #         component: backend
 #         app: sausage-store
 #         __path__: /var/sausage-store/logs/*.log
