pipeline {
    agent any // Выбираем Jenkins агента

    triggers {
        pollSCM('H/5 * * * *') // Запускать будем автоматически по крону примерно раз в 5 минут
    }

    tools {
        maven 'maven-3.8.1' // Для сборки бэкенда нужен Maven
        nodejs 'node-16' // NodeJS нужен для фронта
    }

    stages {
        stage('Build & Test backend') {
            steps {
                dir("backend") {
                    sh 'mvn package' 
                }
            }

            // Передадим результаты тестов в Jenkins
            post {
                success {
                    junit 'backend/target/surefire-reports/**/*.xml' 
                }
            }
        }

        stage('Build frontend') {
            steps {
                dir("frontend") {
                    sh 'npm install'
                    sh 'npm run build'
                }
            }
        }
        // Сохранение артефактов
        stage('Save artifacts') {
            steps {
                archiveArtifacts(artifacts: 'backend/target/my_backend-0.0.1-.jar')
                archiveArtifacts(artifacts: 'frontend/dist/frontend/*')
            }
        // Отправка уведомления об успешной сборке
	    post {
		success{
			sh '''curl -X POST -H 'Content-type: application/json' \
			-d '{"chat_id": "id чата в телеграмме", "text": "Приложение собрано успешно."}' \
			https://api.telegram.org/idбота/sendMessage'''
		}
	    	
	    }
        }
    }
}
