build-backend-code-job:
  stage: build
  cache:
    key: ${CI_PROJECT_DIR}
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository
  only:
    changes:
      - backend/**/*
  script:
    - cd backend
    - mvn package -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
  artifacts:
    paths:
      - backend/target/app-0.0.1.jar

semgrep-sast:
  stage: test
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository

sonarqube-backend-sast:
  stage: test
  image: maven:3.8-openjdk-16
  needs:
    - build-backend-code-job
  only:
    changes:
      - backend/**/*
  script:
    - cd backend
    - |
      mvn verify sonar:sonar \
      -Dsonar.projectName="БЭКЭНД" \
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACK} \
      -Dsonar.host.url=${SONARQUBE_URL} \
      -Dsonar.login=${SONAR_LOGIN_BACK} \
      -Dsonar.qualitygate.wait=true

telegram-notification-backend:
  stage: notify
  rules:
    - if: '$CI_COMMIT_MESSAGE =~ /send notification/'
      changes:
        - backend/**/*
  script:
    - |
      curl -X POST -H "Content-type: application/json" \
      --data "{
      \"chat_id\": id_чата,
      \"text\": \"Собан backend\n${CI_PROJECT_URL}/-/jobs/artifacts/${CI_COMMIT_SHA}/download?job=build-backend-code-job\"
      }" \
      https://api.telegram.org/id_бота/sendMessage
  needs:
